version: '3.5'
services:
  api:
    container_name: locapy_api
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    networks:
      - locapy_api
    depends_on:
      - migration
      - postgres

  collectstatic:
    container_name: collectstatic
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/app
    networks:
      - locapy_api
    depends_on:
      - postgres

  migration:
    container_name: migration
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: python manage.py migrate
    volumes:
      - .:/app
    networks:
      - locapy_api
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:10.7
    environment:
      - POSTGRES_USER=panda_user
      - POSTGRES_DB=Locapy
      - POSTGRES_PASSWORD=Panda@2018
    volumes:
      - .:/app
    ports:
      - 5432:5432
    networks:
      - locapy_api

networks:
  locapy_api:
    external:
      name: locapy_api
