version: '3.5'
services:
  api:
    container_name: locapy_api
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    networks:
      - locapy_api
    depends_on:
      - migration
      - postgres
      - rabbitmq

  collectstatic:
    container_name: collectstatic
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/app
    networks:
      - locapy_api
    depends_on:
      - postgres
      - migration

  migration:
    container_name: migration
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: python manage.py migrate
    volumes:
      - .:/app
    networks:
      - locapy_api
    depends_on:
      - postgres
      - rabbitmq

  celery-worker:
    container_name: celery-worker
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: celery -A locapy worker -l INFO
    volumes:
      - .:/app
    networks:
      - locapy_api
    depends_on:
      - postgres
      - rabbitmq
      - migration

  celery-beat:
    container_name: celery-beat
    image: locapy_api:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        requirements: dev
    command: celery -A locapy beat --pidfile=/tmp/celery-beat.pid -l INFO
    volumes:
      - .:/app
    networks:
      - locapy_api
    depends_on:
      - postgres
      - rabbitmq
      - migration

  postgres:
    container_name: postgres
    image: postgres:10.7
    environment:
      - POSTGRES_USER=panda_user
      - POSTGRES_DB=Locapy
      - POSTGRES_PASSWORD=Panda@2018
    volumes:
      - .:/app
    ports:
      - 5432:5432
    networks:
      - locapy_api

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.14
    volumes:
      - ./var/locapy/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - locapy_api

networks:
  locapy_api:
    external:
      name: locapy_api
